<?php

/**
 * @file
 * Contains ox_geovariation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ox_geovariation\GeoVariations;

/**
 * Implements hook_help().
 */
function ox_geovariation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ox_geovariation module.
    case 'help.page.ox_geovariation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides variations in the user interface based on geo location') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_paragraph__TYPE().
 */
function ox_geovariation_preprocess_paragraph__call_to_action(&$variables) {
  GeoVariations::initialiseCtaLinks($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ox_geovariation_preprocess_menu__main(&$variables) {
  GeoVariations::initialiseDonationLinks($variables);
}

/**
 * Implements hook_page_attachments().
 */
function ox_geovariation_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'ox_geovariation/geo';
}
